{
 "title": "AlwaysON  Server Status",
 "description": "General Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(sql_instance)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "options": { "content": "\n$instance\n" },
   "targets": [
    {
     "expr": "sqlserver_hadr_replica_states_replica_synchronization_health{availability_mode_desc=\"SYNCHRONOUS_COMMIT\", sql_instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_hadr_replica_states_replica_synchronization_health{availability_mode_desc=\"SYNCHRONOUS_COMMIT\", sql_instance=\"$instance\"} > 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "expr": "sqlserver_cpu_sqlserver_process_cpu{job=\"telegraf\", measurement_db_type=\"SQLServer\", sql_instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "legendFormat": "__auto",
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "expr": "sqlserver_cpu_other_process_cpu{job=\"telegraf\", measurement_db_type=\"SQLServer\", sql_instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "legendFormat": "__auto",
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_uptime{sql_instance=\"$instance\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BCHR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Buffer cache hit ratio\",sql_instance=~\"$instance\"}",
     "legendFormat": "{{counter}}"
    }
   ]
  },
  {
   "title": "Page Life Expectancy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Page life expectancy\",exported_instance!~\"000|001\",sql_instance=~\"$instance\"}  /60",
     "legendFormat": "{{counter}}"
    }
   ]
  },
  {
   "title": "Deadlock",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(sqlserver_performance{counter=\"Number of Deadlocks/sec\",exported_instance=\"Total\",sql_instance=~\"$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{counter}}",
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Connection memory per connection (bytes)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Log %Free",
   "type": "stat",
   "description": "A modifier pour intégrer les logs",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sqlserver_volume_space_available_space_bytes{sql_instance=\"$instance\"}) / sum(sqlserver_volume_space_total_space_bytes{sql_instance=\"$instance\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data % Free",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sqlserver_volume_space_available_space_bytes{sql_instance=\"$instance\"}) / sum(sqlserver_volume_space_total_space_bytes{sql_instance=\"$instance\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB-OFF",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"$instance\"}",
     "legendFormat": "DBOFFLINE"
    }
   ]
  },
  {
   "title": "Tran/Sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",counter=\"Transactions/sec\",exported_instance!=\"Total\"}[5m])) ",
     "legendFormat": "{{$database_name}}"
    }
   ]
  }
 ]
}