{
 "title": "SQL Server detail per Database",
 "description": "Details per Databases",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": " instance",
    "query": {
     "query": "label_values(sqlserver_server_properties_uptime,sql_instance)"
    }
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": {
     "query": "label_values(sqlserver_database_io_read_bytes{sql_instance=\"$instance\"},database_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_instance_type{sql_instance=\"$instance\"}",
     "legendFormat": "{{ sql_version }}"
    }
   ]
  },
  {
   "title": "General metrics",
   "type": "text",
   "gridPos": { "h": 1, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup/restore throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",exported_instance=~\"$database_name\",counter=\"Backup/Restore Throughput/sec\",exported_instance!=\"Total\"}[5m]))",
     "legendFormat": "Backup/Restore Throughput/sec"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_cpu_count{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_server_memory{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SQL uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_uptime{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Offline databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Log Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Percent Log Used\", sql_instance=\"$instance\", exported_instance=\"$database_name\"}",
     "legendFormat": "{{sql_instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Online databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 1, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_online{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Bad databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recovering{sql_instance=~\"$instance\"}+sqlserver_server_properties_db_recoveryPending{sql_instance=~\"$instance\"}+sqlserver_server_properties_db_suspect{sql_instance=~\"$instance\"}+sqlserver_server_properties_db_restoring{sql_instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Global requests per sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",counter=\"Batch Requests/sec\"}[5m]))",
     "legendFormat": "Batch Requests/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",counter=\"SQL Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Compilations/sec"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",counter=\"SQL Re-Compilations/sec\"}[5m]))",
     "legendFormat": "SQL Re-Compilations/sec"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance{sql_instance=~\"$instance\",counter=\"Buffer cache hit ratio\"})",
     "legendFormat": "Buffer cache hit ratio"
    }
   ]
  },
  {
   "title": "DB filtered metrics",
   "type": "text",
   "gridPos": { "h": 1, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (sqlserver_performance{sql_instance=~\"$instance\",exported_instance=~\"$database_name\",counter=\"Data File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "Data"
    },
    {
     "expr": "sum by (sql_instance) (sqlserver_performance{sql_instance=~\"$instance\",exported_instance=~\"$database_name\",counter=\"Log File(s) Size (KB)\",exported_instance!=\"Total\"})",
     "legendFormat": "TLog"
    }
   ]
  },
  {
   "title": "Transactions per sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",exported_instance=~\"$database_name\",counter=\"Transactions/sec\",exported_instance!=\"Total\"}[5m]))",
     "legendFormat": "1/s"
    }
   ]
  },
  {
   "title": "Database IO throughout",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_read_bytes{sql_instance=~\"$instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_write_bytes{sql_instance=~\"$instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Database IO operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_reads{sql_instance=~\"$instance\",database_name=~\"$database_name\"}[5m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_database_io_writes{sql_instance=~\"$instance\",database_name=~\"$database_name\"}[5m]))  ",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Database LOG Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (database_name) (irate(sqlserver_database_io_write_latency_ms{sql_instance='$instance',database_name=\"$database_name\",file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename)  irate(sqlserver_database_io_writes{sql_instance='$instance',file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval])) ",
     "legendFormat": "{{database_name}}"
    }
   ]
  },
  {
   "title": "Database Data Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (database_name) (irate(sqlserver_database_io_write_latency_ms{sql_instance='$instance',database_name=\"$database_name\",file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename)  irate(sqlserver_database_io_writes{sql_instance='$instance',file_type='ROWS',measurement_db_type=\"SQLServer\",database_name=\"$database_name\"}[$__rate_interval])) ",
     "legendFormat": "Write latency Database: {{database_name}} "
    }
   ]
  },
  {
   "title": "Database LOG Write Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (database_name) (irate(sqlserver_database_io_read_latency_ms{sql_instance='$instance',database_name=\"$database_name\",file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename)  irate(sqlserver_database_io_reads{sql_instance='$instance',file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval])) ",
     "legendFormat": "{{database_name}}"
    }
   ]
  },
  {
   "title": "Database Data Reads Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (database_name) (irate(sqlserver_database_io_read_latency_ms{sql_instance=\"$instance\",database_name=\"$database_name\",file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename) irate(sqlserver_database_io_reads{sql_instance='$instance',file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]))",
     "legendFormat": "Read latency Database: {{database_name}} "
    }
   ]
  }
 ]
}