{
 "title": "SQL Server Monitoring",
 "description": "SQl Server Status Details",
 "tags": [
  "prometheus",
  "SQL Server"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(sqlserver_server_properties_uptime,sql_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_instance_type{sql_instance=\"$instance\"}",
     "legendFormat": "{{ sql_version }}"
    }
   ]
  },
  {
   "title": "Details per database, click on link below",
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": {
    "content": "# COMMENT\n\nLink to details panel per database:[(https://grafana.group.local/d/ddnysatk3aozkd/sql-server-detail-per-database?${__all_variables})"
   }
  },
  {
   "title": "Databases Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Helathy ",
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Buffer cache hit ratio\",sql_instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Buffer pool rate (bytes/sec)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffer pool rate (bytes/sec)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "CPU: $instance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sqlserver_cpu_sqlserver_process_cpu{sql_instance=\"$instance\"}[5m])",
     "legendFormat": "SQLCPU"
    },
    {
     "expr": "avg_over_time(sqlserver_cpu_other_process_cpu{sql_instance=\"$instance\"}[5m]) ",
     "legendFormat": "OTHER"
    },
    {
     "expr": "avg_over_time(sqlserver_cpu_system_idle_cpu{sql_instance=\"$instance\"}[5m]) ",
     "legendFormat": "IDLE_CPU"
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_online{sql_instance=~\"^$instance\"}",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recoveryPending{sql_instance=~\"^$instance\"}",
     "measurement": "State RECOVERY_PENDING",
     "query": "SELECT \"total\" FROM \"State RECOVERY_PENDING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Alert list firing",
   "type": "alertlist",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tran/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sql_instance) (irate(sqlserver_performance{sql_instance=~\"$instance\",counter=\"Transactions/sec\",exported_instance!=\"Total\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Connection memory per connection (bytes)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_cpu_count{sql_instance=~\"^$instance\"}",
     "measurement": "Recovery Model SIMPLE",
     "query": "SELECT \"total\" FROM \"Recovery Model SIMPLE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RECOVERING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_recovering{sql_instance=~\"^$instance\"}",
     "measurement": "State RECOVERING",
     "query": "SELECT \"total\" FROM \"State RECOVERING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "RESTORING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_restoring{sql_instance=~\"^$instance\"}",
     "measurement": "State RESTORING",
     "query": "SELECT \"total\" FROM \"State RESTORING\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Deadlock/sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(sqlserver_performance{counter=\"Number of Deadlocks/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Connection memory per connection (bytes)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "PLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Page life expectancy\",exported_instance!~\"000|001\",sql_instance=~\"^$instance\"} /60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{counter}}",
     "measurement": "Page life expectancy | Buffer Manager",
     "query": "SELECT mean(\"value\") FROM \"Page life expectancy | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerk Buffer Pool",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Buffer Pool\",sql_instance=~\"^$instance\"}"
    }
   ]
  },
  {
   "title": "Version Store Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Version Store Size (KB)\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Percent Log Used | mssqlsystemresource | Databases",
     "query": "SELECT mean(\"value\") FROM \"Percent Log Used | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Total Server Memory (KB)\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Target Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Target Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "SUSPECT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_suspect{sql_instance=~\"^$instance\"}",
     "measurement": "State SUSPECT",
     "query": "SELECT \"total\" FROM \"State SUSPECT\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_server_properties_db_offline{sql_instance=~\"^$instance\"}",
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "% Data Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sqlserver_volume_space_available_space_bytes{sql_instance=\"$instance\"}) / sum(sqlserver_volume_space_total_space_bytes{sql_instance=\"$instance\"}) * 100",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Buffer pool rate (bytes/sec)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffer pool rate (bytes/sec)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Total % Log Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Percent Log Used\", sql_instance=\"$instance\", exported_instance=\"Total\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Buffer pool rate (bytes/sec)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Buffer pool rate (bytes/sec)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Total Data File Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Data File(s) Size (KB)\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}",
     "measurement": "Performance metrics",
     "query": "SELECT \"Point In Time Recovery\" FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter",
     "select": [
      [
       { "params": [ "Point In Time Recovery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
     ]
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Used memory (KB)\",exported_instance=\"internal\",sql_instance=~\"^$instance\"} /100\r\n",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Total Server Memory (KB) | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Total Server Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Memory Grant Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Memory Grants Pending\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Memory Grants Pending | Memory Manager",
     "query": "SELECT mean(\"value\") FROM \"Memory Grants Pending | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Free Space tempdb",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Free Space in tempdb (KB)\",sql_instance=~\"^$instance\"}",
     "measurement": "Data File(s) Size (KB) | mssqlsystemresource | Databases",
     "query": "SELECT \"value\" FROM \"Data File(s) Size (KB) | mssqlsystemresource | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Active Temp Tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"Active Temp Tables\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Performance metrics",
     "query": "SELECT mean(\"Page File Usage (%)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Page File Usage (%)" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" }
     ]
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_performance{counter=\"User Connections\",sql_instance=~\"^$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "User Connections | General Statistics",
     "query": "SELECT mean(\"value\") FROM \"User Connections | General Statistics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
     ]
    }
   ]
  },
  {
   "title": "Quick Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SQL Cpu-Other",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "expr": "avg_over_time(sqlserver_cpu_sqlserver_process_cpu{job=\"telegraf\", measurement_db_type=\"SQLServer\", sql_instance=~\"$instance\"}[5m]) ",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "legendFormat": "SQL_CPU",
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "expr": "avg_over_time(sqlserver_cpu_other_process_cpu{job=\"telegraf\", measurement_db_type=\"SQLServer\", sql_instance=~\"$instance\"}[5m]) ",
       "legendFormat": "OTHER CPU"
      },
      {
       "expr": "avg_over_time(sqlserver_cpu_system_idle_cpu{sql_instance=\"$instance\"}[5m]) ",
       "legendFormat": "IDLE CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Log Files Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Log File(s) Size (KB)\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}",
       "measurement": "Recovery Model BULK_LOGGED",
       "query": "SELECT \"total\" FROM \"Recovery Model BULK_LOGGED\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "Total Log Files Used Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 3, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Log File(s) Used Size (KB)\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}",
       "measurement": "Recovery Model FULL",
       "query": "SELECT \"total\" FROM \"Recovery Model FULL\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
       ]
      }
     ]
    },
    {
     "title": "Checkpoint pages/sec",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Checkpoint pages/sec\",sql_instance=~\"^$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Performance metrics",
       "query": "SELECT mean(\"Connection memory per connection (bytes)\") FROM \"Performance metrics\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance metrics' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         {
          "params": [
           "Connection memory per connection (bytes)"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance metrics" }
       ]
      }
     ]
    },
    {
     "title": "Free List Stalls/sec",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Free list stalls/sec\",sql_instance=~\"^$instance\"}",
       "measurement": "Free list stalls/sec | Buffer Manager",
       "query": "SELECT \"value\" FROM \"Free list stalls/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    },
    {
     "title": "Page lookups/sec",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 13, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=\"Page lookups/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Performance metrics",
       "query": "SELECT mean(\"Total target memory ratio\") FROM \"Performance metrics\" WHERE \"type\" = 'Performance metrics' AND \"servername\" =~ /$Instance$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "Total target memory ratio" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance metrics" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Backup/Restore Throughput",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Backup/Restore Throughput/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Backup/Restore Throughput/sec | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Backup/Restore Throughput/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database size trend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Database | Rows Size",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance{counter=\"Data File(s) Size (KB)\",sql_instance=~\"^$instance\"} ",
       "legendFormat": "{{exported_instance}}",
       "measurement": "Rows size (bytes)",
       "query": "SELECT * FROM \"Rows size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
       ]
      }
     ]
    },
    {
     "title": "Database | Log Size",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sqlserver_performance{counter=\"Log File(s) Size (KB)\",sql_instance=~\"^$instance\"}",
       "legendFormat": "{{exported_instance}}",
       "measurement": "Log size (bytes)",
       "query": "SELECT * FROM \"Log size (bytes)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database size' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database size" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Performance counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SQL Server Stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=\"Batch Requests/sec\",sql_instance=~\"^$instance\"}[$__range]) ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Batch Requests/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "irate(sqlserver_performance{counter=\"Logins/sec\",sql_instance=~\"^$instance\"}[$__range]) ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Logins/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "irate(sqlserver_performance{counter=\"Logouts/sec\",sql_instance=~\"^$instance\"}[$__range]) ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Logouts/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "irate(sqlserver_performance{counter=\"SQL Compilations/sec\",sql_instance=~\"^$instance\"}[$__range]) ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "SQL Compilations/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "irate(sqlserver_performance{counter=\"SQL Re-Compilations/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "SQL Re-Compilations/sec",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "irate(sqlserver_performance{counter=\"Processes blocked\",sql_instance=~\"^$instance\"}[$__range]) ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Processes blocked",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Databases Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Transactions/sec",
       "expr": "irate(sqlserver_performance{counter=\"Transactions/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Transactions/sec",
       "measurement": "Transactions/sec | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Write Transactions/sec",
       "expr": "irate(sqlserver_performance{counter=\"Write Transactions/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Write Transactions/sec",
       "measurement": "Write Transactions/sec | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Write Transactions/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Log Flushes/sec",
       "expr": "irate(sqlserver_performance{counter=\"Log Flushes/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Log Flushes/sec",
       "measurement": "Log Flushes/sec | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Log Flushes/sec | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Log Flush Wait Time",
       "expr": "irate(sqlserver_performance{counter=\"Log Flush Wait Time\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Log Flush Wait Time",
       "measurement": "Log Flush Wait Time | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Log Flush Wait Time | _Total | Databases\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Lock Timeouts/sec",
       "expr": "irate(sqlserver_performance{counter=\"Lock Timeouts/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Lock Timeouts/sec",
       "measurement": "Lock Timeouts/sec | _Total | Locks",
       "query": "SELECT mean(\"value\") FROM \"Lock Timeouts/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Number of Deadlocks/sec",
       "expr": "irate(sqlserver_performance{counter=\"Number of Deadlocks/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Number of Deadlocks/sec",
       "measurement": "Number of Deadlocks/sec | _Total | Locks",
       "query": "SELECT mean(\"value\") FROM \"Number of Deadlocks/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Lock Waits/sec",
       "expr": "irate(sqlserver_performance_value{counter=\"Lock Waits/sec\",database_name=\"master\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Lock Waits/sec",
       "measurement": "Lock Waits/sec | _Total | Locks",
       "query": "SELECT mean(\"value\") FROM \"Lock Waits/sec | _Total | Locks\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Latch Waits/sec",
       "expr": "irate(sqlserver_performance{counter=\"Latch Waits/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Latch Waits/sec",
       "measurement": "Latch Waits/sec | Latches",
       "query": "SELECT mean(\"value\") FROM \"Latch Waits/sec | Latches\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    },
    {
     "title": "Buffer Cache - Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Full Scans/sec",
       "expr": "irate(sqlserver_performance{counter=\"Full Scans/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Full Scans/sec",
       "measurement": "Full Scans/sec | Access Methods",
       "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Index Searches/sec",
       "expr": "irate(sqlserver_performance{counter=\"Index Searches/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Index Searches/sec",
       "measurement": "Index Searches/sec | Access Methods",
       "query": "SELECT mean(\"value\") FROM \"Index Searches/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Page Splits/sec",
       "expr": "irate(sqlserver_performance{counter=\"Page Splits/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Page Splits/sec",
       "measurement": "Page Splits/sec | Access Methods",
       "query": "SELECT mean(\"value\") FROM \"Page Splits/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Page lookups/sec",
       "expr": "irate(sqlserver_performance{counter=\"Page lookups/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Page lookups/sec",
       "measurement": "Page lookups/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Page lookups/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Page reads/sec",
       "expr": "irate(sqlserver_performance{counter=\"Page reads/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Page reads/sec",
       "measurement": "Page reads/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Page reads/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Page writes/sec",
       "expr": "irate(sqlserver_performance{counter=\"Page writes/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Page writes/sec",
       "measurement": "Page writes/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Page writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Readahead pages/sec",
       "expr": "irate(sqlserver_performance{counter=\"Readahead pages/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Readahead pages/sec",
       "measurement": "Readahead pages/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Readahead pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Lazy writes/sec",
       "expr": "irate(sqlserver_performance{counter=\"Lazy writes/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Lazy writes/sec",
       "measurement": "Lazy writes/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Lazy writes/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Checkpoint pages/sec",
       "expr": "irate(sqlserver_performance{counter=\"Checkpoint pages/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Checkpoint pages/sec",
       "measurement": "Checkpoint pages/sec | Buffer Manager",
       "query": "SELECT mean(\"value\") FROM \"Checkpoint pages/sec | Buffer Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    },
    {
     "title": "Memory Manager",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "alias": "SQL Cache",
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Transactions Cache (Object Store)\",sql_instance=~\"^$instance\"}",
       "legendFormat": "SQL Cache",
       "measurement": "SQL Cache Memory (KB) | Memory Manager",
       "query": "SELECT \"value\" FROM \"SQL Cache Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Optimizer",
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"SQL Optimizer\",sql_instance=~\"^$instance\"}",
       "legendFormat": "Optimizer",
       "measurement": "Optimizer Memory (KB) | Memory Manager",
       "query": "SELECT \"value\" FROM \"Optimizer Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Log Pool",
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Log Pool\",sql_instance=~\"^$instance\"}",
       "legendFormat": "Log Pool",
       "measurement": "Log Pool Memory (KB) | Memory Manager",
       "query": "SELECT \"value\" FROM \"Log Pool Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Lock",
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"SQL Plans\", sql_instance=\"$instance\"}",
       "legendFormat": "plan",
       "measurement": "Lock Memory (KB) | Memory Manager",
       "query": "SELECT \"value\" FROM \"Lock Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      },
      {
       "alias": "Connection",
       "expr": "sqlserver_memory_clerks_size_kb{clerk_type=\"Connection Pool\",sql_instance=~\"^$instance\"} ",
       "legendFormat": "Connection",
       "measurement": "Connection Memory (KB) | Memory Manager",
       "query": "SELECT \"value\" FROM \"Connection Memory (KB) | Memory Manager\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    },
    {
     "title": "Log activities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Log Flushes/sec",
       "expr": "irate(sqlserver_performance{counter=\"Log Flushes/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Log Flushes/sec",
       "measurement": "Log Flushes/sec | _Total | Databases",
       "query": "SELECT mean(\"value\") FROM \"Full Scans/sec | Access Methods\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Performance counters' AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Performance counters" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory break down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used memory by Instance",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_performance{counter=\"Used memory (KB)\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{exported_instance}}",
       "measurement": "Memory breakdown (%)",
       "query": "SELECT * FROM \"Memory breakdown (%)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Memory clerk' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Memory clerk" }
       ]
      }
     ]
    },
    {
     "title": "Memory Clerks Size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "irate(sqlserver_memory_clerks_size_kb{clerk_type=~\"^SQL.*\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{clerk_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "IO/sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=~\"^Disk.*IO.*\",exported_instance=\"internal\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{counter}}"
      }
     ]
    },
    {
     "title": "DATA | Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_bytes{file_type=\"ROWS\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Read Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_read_bytes{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "DATA | Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_bytes{file_type=\"ROWS\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows writes (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Rows writes (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Write Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(sqlserver_database_io_write_bytes{file_type=\"LOG\",sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{database_name}}",
       "measurement": "Log reads (bytes/sec)",
       "query": "SELECT \"AdventureWorks2014\", \"Australian\", \"DOC.Azure\", \"ResumeCloud\", \"ngMon\", \"tempdb\" FROM \"Log reads (bytes/sec)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database IO' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database IO" }
       ]
      }
     ]
    },
    {
     "title": "Wait Tasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_wait_time_ms{sql_instance='$instance',measurement_db_type=\"SQLServer\"}[$__range])/rate(sqlserver_waitstats_waiting_tasks_count{sql_instance='$instance',measurement_db_type=\"SQLServer\"}[$__range])",
       "legendFormat": "{{wait_category}} {{wait_type}}"
      }
     ]
    },
    {
     "title": "Wait Tasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_waiting_tasks_count{sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{wait_category}} {{wait_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DATA | Read Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sum by (database_name) (irate(sqlserver_database_io_read_latency_ms{sql_instance='$instance',database_name!~\"master|model|msdb\",file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename) irate(sqlserver_database_io_reads{sql_instance='$instance',file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]))",
       "legendFormat": "__auto",
       "measurement": "Rows read latency (ms)",
       "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Read Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sum by (database_name) (irate(sqlserver_database_io_read_latency_ms{sql_instance='$instance',database_name!~\"master|model|msdb\",file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename) irate(sqlserver_database_io_reads{sql_instance='$instance',file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]))",
       "legendFormat": "{{database_name}}",
       "measurement": "Log read latency (ms)",
       "query": "SELECT * FROM \"Log read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "DATA | Write Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sum by (database_name) (irate(sqlserver_database_io_write_latency_ms{sql_instance='$instance',database_name!~\"master|model|msdb\",file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename) irate(sqlserver_database_io_writes{sql_instance='$instance',file_type='ROWS',measurement_db_type=\"SQLServer\"}[$__rate_interval]))",
       "legendFormat": "{{database_name}}",
       "measurement": "Rows read latency (ms)",
       "query": "SELECT * FROM \"Rows read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    },
    {
     "title": "LOG | Write Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "sum by (database_name) (irate(sqlserver_database_io_write_latency_ms{sql_instance='$instance',database_name!~\"master|model|msdb\",file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]) / on (database_name,logical_filename) irate(sqlserver_database_io_writes{sql_instance='$instance',file_type='LOG',measurement_db_type=\"SQLServer\"}[$__rate_interval]))",
       "legendFormat": "{{database_name}}",
       "measurement": "Log read latency (ms)",
       "query": "SELECT * FROM \"Log read latency (ms)\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database stats' AND $timeFilter",
       "select": [
        [
         { "params": [ "*" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "Database stats" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Waits Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wait Time ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_wait_time_ms{sql_instance='$instance',measurement_db_type=\"SQLServer\"}[$__range])/rate(sqlserver_waitstats_waiting_tasks_count{sql_instance='$instance',measurement_db_type=\"SQLServer\"}[$__range]) > 0.1",
       "legendFormat": "{{wait_type}}"
      }
     ]
    },
    {
     "title": "Wait Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(sqlserver_waitstats_waiting_tasks_count{sql_instance=~\"^$instance\"}[$__range])",
       "legendFormat": "{{wait_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OUT | Bytes sent to Replica/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=\"Bytes Sent to Replica/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}}",
       "measurement": "Bytes Sent to Replica/sec | _Total | Availability Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "IN | Bytes received from Replica/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=\"Bytes Received from Replica/sec\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}}",
       "measurement": "Bytes Received from Replica/sec | _Total | Availability Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Transaction Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sqlserver_performance{counter=\"Transaction Delay\",exported_instance=\"Total\",sql_instance=~\"^$instance\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}} {{exported_instance}}",
       "measurement": "Transaction Delay | _Total | Database Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Mirrored Write Transactions/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(sqlserver_performance{counter=\"Mirrored Write Transactions/sec\",sql_instance=~\"^$instance\"}[$__range])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{counter}} {{exported_instance}}",
       "measurement": "Mirrored Write Transactions/sec | _Total | Database Replica",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Performance counters" },
        { "condition": "AND", "key": "servername", "operator": "=~", "value": "/^$Instance$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}